### ISSUE TITLE
Fails to run with keycloak v10 / v11

### ISSUE THREAD

**Issue by dbroadhurst** [frankhefeng/aws-cdk-fargate-keycloak#2]
I've tried to upgrade to keycloak v11.0.0 but the fargate task fails. Still investigating but wondered if this is a known issue.

**Comment by frankhefeng** [comment]
I'll have a look

**Comment by frankhefeng** [comment]
Fixed.  JDBC_PARAMS: 'useSSL=false' added as keycloak v11 use SSL to connect MySQL by default.
Also, memoryLimitMiB increased to 1024 as sometimes Fargate task crashes.

**Comment by dbroadhurst** [comment]
Thanks Frank
