### ISSUE TITLE
Not able to setup the SMTP server

### ISSUE THREAD

**Issue by dbroadhurst** [frankhefeng/aws-cdk-fargate-keycloak#5]
I can get the SMTP connection working with a local docker version but when I use the CDK version the email SMTP server fails to connect even though I'm using the exact same credentials. I think outbound traffic is being blocked

**Comment by frankhefeng** [comment]
Please refer to this:
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/

Other than the solution provided, I would prefer to use AWS SES to avoid this touble.
